### ISSUE TITLE
Storing preferences that involves file and images

### ISSUE THREAD

**Issue by abishekrsrikaanth** [GeniusTS/preferences#2]
How do I go about storing preferences that involve storing files and images?

**Comment by aboudeh87** [comment]
usually for files and images, I use  javascript library in the frontend view to return the url of the file (Ex. Elfinder), and in the backend the validation will be `url`.

And also you can make some custom logic in the controller in `app` directory of the project like

```
public function update(SettingsRequest $request) {
   // some code here

   parent::update($request);
}

```

**Comment by abishekrsrikaanth** [comment]
If the package exposed events `beforeUpdatingPreference` and `afterUpdatingPreference` might provide better options. Would you be able to add these events in that can be subscribed to do this?

**Comment by aboudeh87** [comment]
Ok i will add it
